#include "WallpaperApplier.h"
#include "ConfigManager.h"
#include <QProcess>
#include <QFileInfo>
#include <QStringList>
#include <QFile>
#include <QTextStream>
#include <QStandardPaths>
#include <QDir>
#include <QThread>
#include <QImage>
#include <QTransform>
#include <QDebug>
#include <QRandomGenerator>

static const QStringList VIDEO_EXTS = {
    "mp4","mkv","avi","webm","mov","gif","flv","wmv"
};

bool WallpaperApplier::isVideoFile(const QString &path)
{
    return VIDEO_EXTS.contains(QFileInfo(path).suffix().toLower());
}

QString WallpaperApplier::fillModeToHyprpaper(FillMode mode)
{
    switch (mode) {
        case FillMode::Cover:   return "cover";
        case FillMode::Contain: return "contain";
        default:                return "cover";
    }
}

static QString mpvOptions(int fillIdx, int rotIdx, bool audio, int volume)
{
    QStringList opts;
    opts << "--loop";
    switch (fillIdx) {
        case 0:  opts << "--panscan=1.0";    break;
        default: opts << "--keepaspect=yes"; break;
    }
    switch (rotIdx) {
        case 1: opts << "--video-rotate=90";  break;
        case 2: opts << "--video-rotate=180"; break;
        case 3: opts << "--video-rotate=270"; break;
        default: break;
    }
    if (!audio)
        opts << "--no-audio";
    else
        opts << QString("--volume=%1").arg(volume);
    return opts.join(" ");
}

QString WallpaperApplier::prepareRotatedImage(const QString &src, WallpaperRotation rot)
{
    if (rot == WallpaperRotation::Normal) return QString();
    QImage img(src);
    if (img.isNull()) { qWarning() << "prepareRotatedImage: cannot load" << src; return QString(); }
    QTransform t;
    switch (rot) {
        case WallpaperRotation::Clockwise90:  t.rotate(90);  break;
        case WallpaperRotation::Clockwise180: t.rotate(180); break;
        case WallpaperRotation::Clockwise270: t.rotate(270); break;
        default: break;
    }
    QImage result = img.transformed(t, Qt::SmoothTransformation);
    QString cacheDir = QStandardPaths::writableLocation(QStandardPaths::CacheLocation) + "/HyprWall";
    QDir().mkpath(cacheDir);
    QString tmp = cacheDir + "/" + QFileInfo(src).baseName() + "_rot.png";
    if (!result.save(tmp, "PNG")) { qWarning() << "prepareRotatedImage: save failed" << tmp; return QString(); }
    return tmp;
}

// Write hyprpaper.conf for all image monitors
static void writeHyprpaperConf(const QMap<QString, WallpaperConfig> &all)
{
    QString confDir = QStandardPaths::writableLocation(QStandardPaths::ConfigLocation) + "/hypr";
    QDir().mkpath(confDir);
    QFile f(confDir + "/hyprpaper.conf");
    if (!f.open(QIODevice::WriteOnly | QIODevice::Text)) return;
    QTextStream ts(&f);
    ts << "# Generated by HyprWall\n\nsplash = false\n\n";
    for (auto it = all.cbegin(); it != all.cend(); ++it) {
        const WallpaperConfig &c = it.value();
        if (c.filePath.isEmpty() || WallpaperApplier::isVideoFile(c.filePath)) continue;
        QString path = c.filePath;
        QString rot  = WallpaperApplier::prepareRotatedImage(path, c.rotation);
        if (!rot.isEmpty()) path = rot;
        ts << "wallpaper {\n"
           << "    monitor = " << c.monitorName << "\n"
           << "    path = " << path << "\n"
           << "    fit_mode = " << WallpaperApplier::fillModeToHyprpaper(c.fillMode) << "\n"
           << "}\n\n";
    }
}

// Apply a single-monitor image via hyprpaper IPC (hyprpaper must be running)
static bool applyImageIpc(const WallpaperConfig &cfg)
{
    QString path    = cfg.filePath;
    QString rotPath = WallpaperApplier::prepareRotatedImage(path, cfg.rotation);
    if (!rotPath.isEmpty()) path = rotPath;
    QString fitMode = WallpaperApplier::fillModeToHyprpaper(cfg.fillMode);
    QString ipcArg  = QString("%1, %2, %3").arg(cfg.monitorName, path, fitMode);
    QProcess p;
    p.start("hyprctl", {"hyprpaper", "wallpaper", ipcArg});
    p.waitForFinished(3000);
    QString out = p.readAllStandardOutput().trimmed();
    return !out.toLower().contains("error") && !out.toLower().contains("bad");
}

bool WallpaperApplier::apply(const WallpaperConfig &cfg)
{
    if (cfg.filePath.isEmpty()) { qWarning() << "apply: empty filePath"; return false; }

    if (isVideoFile(cfg.filePath)) {
        // Kill hyprpaper IPC for this monitor first (set it to blank)
        // then stop any existing mpvpaper and start fresh
        stopVideo(cfg.monitorName);
        QString opts = mpvOptions(
            static_cast<int>(cfg.fillMode),
            static_cast<int>(cfg.rotation),
            cfg.audioEnabled, cfg.audioVolume);
        QStringList args;
        args << "-o" << opts << cfg.monitorName << cfg.filePath;
        qDebug() << "mpvpaper" << args;
        return QProcess::startDetached("mpvpaper", args);
    }

    // Image: try IPC first
    bool running = false;
    {
        QProcess chk;
        chk.start("pgrep", {"-x", "hyprpaper"});
        chk.waitForFinished(1000);
        running = !chk.readAllStandardOutput().trimmed().isEmpty();
    }

    if (running) {
        if (applyImageIpc(cfg)) return true;
        qDebug() << "IPC failed, restarting hyprpaper...";
    }

    auto &cm = ConfigManager::instance();
    cm.setConfig(cfg.monitorName, cfg);
    writeHyprpaperConf(cm.configs());
    QProcess::execute("pkill", {"-x", "hyprpaper"});
    QThread::msleep(400);
    return QProcess::startDetached("hyprpaper", {});
}

void WallpaperApplier::applyAll(const QMap<QString, WallpaperConfig> &configs)
{
    bool hasImages = false;
    for (auto it = configs.cbegin(); it != configs.cend(); ++it)
        if (!it.value().filePath.isEmpty() && !isVideoFile(it.value().filePath))
            hasImages = true;

    if (hasImages) {
        writeHyprpaperConf(configs);
        QProcess::execute("pkill", {"-x", "hyprpaper"});
        QThread::msleep(400);
        QProcess::startDetached("hyprpaper", {});
        QThread::msleep(600);
        for (auto it = configs.cbegin(); it != configs.cend(); ++it) {
            const WallpaperConfig &cfg = it.value();
            if (cfg.filePath.isEmpty() || isVideoFile(cfg.filePath)) continue;
            applyImageIpc(cfg);
        }
    }

    for (auto it = configs.cbegin(); it != configs.cend(); ++it) {
        const WallpaperConfig &cfg = it.value();
        if (cfg.filePath.isEmpty() || !isVideoFile(cfg.filePath)) continue;
        stopVideo(cfg.monitorName);
        QString opts = mpvOptions(
            static_cast<int>(cfg.fillMode),
            static_cast<int>(cfg.rotation),
            cfg.audioEnabled, cfg.audioVolume);
        QStringList args;
        args << "-o" << opts << cfg.monitorName << cfg.filePath;
        QProcess::startDetached("mpvpaper", args);
    }
}

void WallpaperApplier::stopVideo(const QString &monitor)
{
    // Kill mpvpaper for this specific monitor
    QProcess::execute("pkill", {"-f", QString("mpvpaper.*%1").arg(monitor)});
    QThread::msleep(200);
}

void WallpaperApplier::toggleAudio(const QString &monitor)
{
    auto &cm = ConfigManager::instance();
    cm.load();
    WallpaperConfig cfg = cm.getConfig(monitor);
    cfg.audioEnabled = !cfg.audioEnabled;
    cm.setConfig(monitor, cfg);
    cm.save();
    apply(cfg);
}

bool WallpaperApplier::applySlideshowTick(const QString &monitor,
                                           const QList<GalleryItem> &gallery,
                                           int mode)
{
    if (gallery.isEmpty()) return false;

    // Filter gallery by mode: 0=photos only, 1=videos only, 2=both
    QList<GalleryItem> filtered;
    for (const GalleryItem &item : gallery) {
        if (mode == 0 && item.isVideo)  continue;
        if (mode == 1 && !item.isVideo) continue;
        filtered << item;
    }
    if (filtered.isEmpty()) filtered = gallery; // fallback: use all if filter yields nothing

    int idx = static_cast<int>(QRandomGenerator::global()->bounded(
                  static_cast<quint32>(filtered.size())));
    const GalleryItem &item = filtered.at(idx);

    WallpaperConfig cfg;
    cfg.monitorName  = monitor;
    cfg.filePath     = item.path;
    cfg.fillMode     = FillMode::Cover;
    cfg.rotation     = WallpaperRotation::Normal;
    cfg.audioEnabled = false;  // slideshow always silent
    cfg.audioVolume  = 0;

    if (item.isVideo) {
        // For video in slideshow: kill hyprpaper IPC doesn't matter, just stop old mpvpaper
        stopVideo(monitor);
        QString opts = mpvOptions(0, 0, false, 0); // cover, 0deg, no audio
        QStringList args;
        args << "-o" << opts << monitor << item.path;
        qDebug() << "slideshow mpvpaper" << args;
        return QProcess::startDetached("mpvpaper", args);
    } else {
        return apply(cfg);
    }
}
