#include "WallpaperApplier.h"
#include "ConfigManager.h"
#include <QProcess>
#include <QFileInfo>
#include <QStringList>
#include <QFile>
#include <QTextStream>
#include <QStandardPaths>
#include <QDir>
#include <QThread>
#include <QImage>
#include <QTransform>
#include <QDebug>

static const QStringList VIDEO_EXTS = {
    "mp4","mkv","avi","webm","mov","gif","flv","wmv"
};

bool WallpaperApplier::isVideoFile(const QString &path)
{
    return VIDEO_EXTS.contains(QFileInfo(path).suffix().toLower());
}

QString WallpaperApplier::fillModeToHyprpaper(FillMode mode)
{
    switch (mode) {
        case FillMode::Cover:   return "cover";
        case FillMode::Contain: return "contain";
        case FillMode::Tile:    return "tile";
        case FillMode::Fill:    return "fill";
        default:                return "cover";
    }
}

// Поворачивает/отражает изображение программно и сохраняет во временный файл
QString WallpaperApplier::prepareRotatedImage(const QString &src, WallpaperRotation rot)
{
    if (rot == WallpaperRotation::Normal) return QString(); // не нужно

    QImage img(src);
    if (img.isNull()) {
        qWarning() << "prepareRotatedImage: cannot load" << src;
        return QString();
    }

    QTransform t;
    bool mirrored = false;
    switch (rot) {
        case WallpaperRotation::Clockwise90:    t.rotate(90);   break;
        case WallpaperRotation::Clockwise180:   t.rotate(180);  break;
        case WallpaperRotation::Clockwise270:   t.rotate(270);  break;
        case WallpaperRotation::FlipHorizontal: mirrored = true; break;
        case WallpaperRotation::FlipVertical:   t.rotate(180); mirrored = true; break; // флип V = flip H + 180°
        default: break;
    }

    QImage result;
    if (mirrored)
        result = img.transformed(t).mirrored(true, false);
    else
        result = img.transformed(t, Qt::SmoothTransformation);

    // Сохраняем во временный файл
    QString cacheDir = QStandardPaths::writableLocation(QStandardPaths::CacheLocation) + "/HyprWall";
    QDir().mkpath(cacheDir);
    QString tmpPath = cacheDir + "/" + QFileInfo(src).baseName() + "_rot.png";
    if (!result.save(tmpPath, "PNG")) {
        qWarning() << "prepareRotatedImage: cannot save" << tmpPath;
        return QString();
    }
    qDebug() << "Rotated image saved to" << tmpPath;
    return tmpPath;
}

static void writeHyprpaperConf(const QMap<QString, WallpaperConfig> &all)
{
    QString confDir = QStandardPaths::writableLocation(QStandardPaths::ConfigLocation) + "/hypr";
    QDir().mkpath(confDir);
    QFile f(confDir + "/hyprpaper.conf");
    if (!f.open(QIODevice::WriteOnly | QIODevice::Text)) return;
    QTextStream ts(&f);
    ts << "# Generated by HyprWall\n\n";
    ts << "splash = false\n\n";
    for (auto it = all.cbegin(); it != all.cend(); ++it) {
        const WallpaperConfig &c = it.value();
        if (c.filePath.isEmpty() || WallpaperApplier::isVideoFile(c.filePath)) continue;
        QString path = c.filePath;
        QString rotPath = WallpaperApplier::prepareRotatedImage(path, c.rotation);
        if (!rotPath.isEmpty()) path = rotPath;
        ts << "wallpaper {\n";
        ts << "    monitor = " << c.monitorName << "\n";
        ts << "    path = " << path << "\n";
        ts << "    fit_mode = " << WallpaperApplier::fillModeToHyprpaper(c.fillMode) << "\n";
        ts << "}\n\n";
    }
    f.close();
    qDebug() << "Wrote hyprpaper.conf";
}

bool WallpaperApplier::apply(const WallpaperConfig &cfg)
{
    if (cfg.filePath.isEmpty()) {
        qWarning() << "apply: empty filePath for" << cfg.monitorName;
        return false;
    }

    // --- Видео ---
    if (isVideoFile(cfg.filePath)) {
        stopVideo(cfg.monitorName);
        // Правильный синтаксис mpvpaper:
        // mpvpaper -o "no-audio --loop" MONITOR FILE
        QString opts = "--loop";
        if (!cfg.audioEnabled)
            opts = "no-audio " + opts;
        else
            opts += QString(" --volume=%1").arg(cfg.audioVolume);
        QStringList args;
        args << "-o" << opts << cfg.monitorName << cfg.filePath;
        qDebug() << "mpvpaper" << args;
        return QProcess::startDetached("mpvpaper", args);
    }

    // --- Статичные обои ---
    // Подготавливаем файл (если нужен поворот)
    QString path = cfg.filePath;
    QString rotPath = prepareRotatedImage(path, cfg.rotation);
    if (!rotPath.isEmpty()) path = rotPath;

    QString fitMode = fillModeToHyprpaper(cfg.fillMode);

    // Проверяем запущен ли hyprpaper
    bool running = false;
    {
        QProcess chk;
        chk.start("pgrep", {"-x", "hyprpaper"});
        chk.waitForFinished(1000);
        running = !chk.readAllStandardOutput().trimmed().isEmpty();
    }

    if (running) {
        // IPC: 'MONITOR, PATH, FIT_MODE'
        QString ipcArg = QString("%1, %2, %3").arg(cfg.monitorName, path, fitMode);
        QProcess p;
        p.start("hyprctl", {"hyprpaper", "wallpaper", ipcArg});
        p.waitForFinished(3000);
        QString out = p.readAllStandardOutput().trimmed();
        qDebug() << "IPC ->" << (out.isEmpty() ? "(empty=ok)" : out);
        if (!out.toLower().contains("error") && !out.toLower().contains("bad"))
            return true;
        qDebug() << "IPC failed, restarting hyprpaper...";
    }

    // Записываем конфиг и перезапускаем
    auto &cm = ConfigManager::instance();
    cm.setConfig(cfg.monitorName, cfg);
    writeHyprpaperConf(cm.configs());
    QProcess::execute("pkill", {"-x", "hyprpaper"});
    QThread::msleep(400);
    bool ok = QProcess::startDetached("hyprpaper", {});
    qDebug() << "hyprpaper restarted:" << ok;
    return ok;
}

void WallpaperApplier::stopVideo(const QString &monitor)
{
    QProcess::execute("pkill", {"-f", QString("mpvpaper.*%1").arg(monitor)});
}

void WallpaperApplier::toggleAudio(const QString &monitor)
{
    auto &cm = ConfigManager::instance();
    cm.load();
    WallpaperConfig cfg = cm.getConfig(monitor);
    cfg.audioEnabled    = !cfg.audioEnabled;
    cm.setConfig(monitor, cfg);
    cm.save();
    apply(cfg);
}
